export default {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_PENDING: 'SIGN_IN_PENDING',
  SIGN_IN_FULFILLED: 'SIGN_IN_FULFILLED',
  SIGN_IN_REJECTED: 'SIGN_IN_REJECTED',
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
}
